export { WhatsappIcon } from './WhatsappIcon';
export { InstagramIcon } from './InstagramIcon';
export { FacebookIcon } from './FacebookIcon';
export { TiktokIcon } from './TiktokIcon';
export { AngleSmallDownIcon } from './AngleSmallDownIcon';
export { MenuIcon } from './MenuIcon';
export { MapsIcon } from './MapsIcon';
export { CheckCircleIcon } from './CheckCircleIcon';
export { WarningIcon } from './WarningIcon';
export { ErrorIcon } from './ErrorIcon';
export type { IconProps } from './types';
